tradepaper/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

from django.contrib import admin
from general import views
from users import views
admin.autodiscover()

urlpatterns = patterns('',
    # pass requests on to other url configs
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^papers/', include('papers.urls', namespace='papers')),
    url(r'^admin/', include(admin.site.urls)),

    # general views
    url(r'^/?$', 'general.views.home', name='home'),
    url(r'^about/?$', 'general.views.about', name='about'),
    url(r'^faq/?$', 'general.views.faq', name='faq'),
    url(r'^shipping/?$', 'general.views.shipping', name='shipping'),
    url(r'^resetpassword/?$', 'general.views.reset_password', name='reset_password'),
    url(r'^resetlink/?$', 'general.views.reset_link', name='reset_link'),

    # users views
    url(r'^login/?$', 'users.views.login', name='login'),
    url(r'^logout/?$', 'users.views.logout', name='logout'),
    url(r'^register/?$', 'users.views.register', name='register'),
    url(r'^myaccount/?$', 'users.views.my_account', name='my_account'),
    url(r'^myaccount/preferences/?$', 'users.views.preferences', name='preferences'),
    url(r'^requests/?$', 'users.views.trades', name='trades'),
    url(r'^manage/?$', 'users.views.manage', name='manage'),
    url(r'^editprofile/?$', 'users.views.edit_profile', name='edit_profile'),

    # papers views
    url(r'^browse/?$', 'papers.views.browse', name='browse'),
)

urlpatterns += staticfiles_urlpatterns()
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

users/urls.py
from django.conf.urls import patterns, url

from users import views
from papers import views as papers_views

urlpatterns = patterns('',
    url(r'^(?P<name>[\w\ ]+)$', views.profile, name='profile'),
)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from papers.models import Message
from shortuuidfield import ShortUUIDField

class UserManager(BaseUserManager):

    def create_user(self, email, password, name, city, is_staff=False, is_superuser=False):
        email = self.normalize_email(email)
        user = self.model(email=email, name=name,
                          city=city, is_active=True,
                          is_staff=is_staff, is_superuser=is_superuser)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, name, city):
        return self.create_user(email, password, name, city, True, True)

class User(AbstractBaseUser):
    id = ShortUUIDField(primary_key=True, unique=True)
    email = models.EmailField(unique=True)
    name = models.CharField(max_length=40, unique=True)
    city = models.CharField(max_length=60, blank=True)
    website = models.URLField(blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name', 'city']

    objects = UserManager()

    def unread_count(self):
        unread_trader = Message.objects.filter(
                sent_by_trader=False
            ).filter(
                trade__trader__id=self.id
            ).filter(
                read=False
            ).count()
        unread_tradee = Message.objects.filter(
                sent_by_trader=True
            ).filter(
                trade__tradee__id=self.id
            ).filter(
                read=False
            ).count()
        return unread_trader + unread_tradee

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True;
        # Returns True if the user has the named permission. If obj is provided,
        # the permission needs to be checked against a specific object instance
    def has_module_perms(self, app_label):
        return True;
        # Returns True if the user has permission to access models in the given app.

    def __str__(self):
        return self.email

users/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib import sessions
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.forms import ModelForm
from django.contrib import messages

from users.models import User

class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password', 'name', 'city']

class LoginForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password',]

class EditProfileForm(ModelForm):
    class Meta:
        model = User
        fields = ['email', 'city', 'website',]

def vet_user(message="You need to be logged in to do that."):
    def _decorated(view):
        def _view(request, *args, **kwargs):
            user = request.user
            if user is None or not user.is_authenticated():
                messages.error(request, message)
                return HttpResponseRedirect("{0}?next={1}".format(reverse('login'), request.path))
            else:
                return view(request, *args, **kwargs)
        return _view
    return _decorated

@vet_user("You need to be logged in to view your account.")
def my_account(request):
    return render(request, 'tradepaper/myaccount.html')

@vet_user("You need to be logged in to manage your account.")
def manage(request):
    return render(request, 'tradepaper/addremove.html', {'listings': user.listing_set.all()})

@vet_user("You need to be logged in to view your preferences.")
def preferences(request):
    return render(request, 'tradepaper/preferences.html')

@vet_user("You need to be logged in to edit your profile.")
def edit_profile(request):
    user = request.user
    form = EditProfileForm(request.POST, instance=user, auto_id="edit%s")

    if request.method != 'POST':
        return render(request, 'tradepaper/editprofile.html', {'form': form})

    email = request.POST.get('email')
    city = request.POST.get('city')
    name = request.POST.get('name')

    if email != user.email:
        if User.objects.filter(email=email).exists():
            messages.error(request, 'That email already has an account')
            return render(request, 'tradepaper/editprofile.html', {'form': form})
    if name != user.name:
        if User.objects.filter(name=name).exists():
            messages.error(request, 'There is already a user with that name')
            return render(request, 'tradepaper/editprofile.html', {'form': form})
    if form.is_valid():
        if (email is not None):
            user.email = email
        if (city is not None):
            user.city = city
        if (name is not None):
            user.name = name
        user.save()
        messages.error(request, 'Successfully Updated!')
    else:
        messages.error(request, 'Please fill in all required fields')
    return render(request, 'tradepaper/editprofile.html', {'form': form})

@vet_user("You need to be logged in to view your requests.")
def trades(request):
    user = request.user
    sent = user.trades_sent.all()
    received = user.trades_received.all()
    return render(request, 'tradepaper/pending-requests.html', 
            {'sent_trades': sent, 'received_trades': received})

def profile(request, name):
    user = get_object_or_404(User, name=name)
    return render(request, 'tradepaper/profile.html', {'user':user})

def login(request):
    form = LoginForm(request.POST, auto_id='login%s')
    if request.method != 'POST':
        return render(request, 'tradepaper/login.html', {'form': form})
    u = authenticate(email=request.POST['email'],
                     password=request.POST['password'])
    form = LoginForm(request.POST, auto_id='login%s', instance=u)
    if u is None:
        messages.error(request, "That email and password didn't match.")
        return render(request, 'tradepaper/login.html', {
                                'form': form})
    if not(u.is_active):
        messages.error(request, "That account has been disabled.")
        return render(request, 'tradepaper/login.html', {
                                'form': form})
    # User has authenticated successfully
    auth_login(request, u)
    next = request.GET.get('next')
    if next is None:
        return HttpResponseRedirect(reverse('my_account'))
    else:
        return HttpResponseRedirect(next)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('home'))

def register(request):
    form = UserForm(request.POST, auto_id='register%s')
    if request.method == 'POST':
        if User.objects.filter(email=request.POST['email']).exists():
            messages.error(request, 'That email already has an account')
            return render(request, 'tradepaper/register.html', {'form': form})
        elif User.objects.filter(name=request.POST['name']).exists():
            messages.error(request, 'There is already a user with that name')
            return render(request, 'tradepaper/register.html', {'form': form})
        if form.is_valid():
            u = User.objects.create_user(
                email = request.POST['email'],
                password = request.POST['password'],
                name = request.POST['name'],
                city = request.POST['city']
            )
            u.save()
            auth_user = authenticate(email=request.POST['email'],
                                    password=request.POST['password'])
            auth_login(request, auth_user)
            return HttpResponseRedirect(reverse('users:profile', args=(u.name,)))
        else:
            messages.error(request, 'Please fill in all required fields')
            return render(request, 'tradepaper/register.html', {'form': form})
    else:
        return render(request, 'tradepaper/register.html', {'form': form})

users/templates/paperapp/login.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Login - trade–paper</title>
	{% load staticfiles %}
	<link href="{% static 'paperapp/styles.css' %}" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>
</head>

<body>

{% include "paperapp/nav-bar.html" %}

<!--Sign Up-->
<div class="login">
	<h1>Log In</h1>
    <h2>Username:</h2>
    <!--text form here-->
    <label for="signup_username"></label>
    <input type="username" name="user[username]" placeholder="username" id="signup_username" data-required="required" class="textfield_effect">

    <h2>Password:</h2>
    <!--text form here-->
    <label for="signup_password"></label>
    <input type="password" name="user[password]" placeholder="password" id="signup_password" data-required="required" class="textfield_effect">

    <div id="loginbutton">
	<input type="submit" value="Submit" class="textfield_effect" id="login_submit">
	</form></div>

    <a href="{% url 'users:register' %}" class="textfield_effect" id="loginregisterlink"> Register </a>

</div>
<!--END Sign Up-->

</body>
</html>

users/templates/paperapp/profile.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Profile - trade–paper</title>
	{% load staticfiles %}
	<link href="{% static "paperapp/styles.css" %}" rel="stylesheet" type="text/css">
	<link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>
</head>

<body>

{% include "paperapp/nav-bar.html" %}

<!--Set Page Title to "username - trade-paper"-->

<!--Profile Header-->
<div class="profile_head">

	<h2>Profile</h2>
	<!--Get avatar-->
    <!--<img src="https://pbs.twimg.com/profile_images/433092997828202496/Lj3L-jIF_bigger.jpeg" />-->
	<!--Get username-->
  	<div id="unamedisp">{{ user.username }}</div>
    <!--Get city location-->
	{% if user.city %}
	    <h3>{{ user.city }}</h3>
	{% endif %}
    <!--Get website if any-->
	{% if user.website %}
	    <h3><a href="">{{ user.website }}</a></h3>
	{% endif %}

</div>
<!--END Profile Header-->

<!--Profile Content-->
<div class="profile">

    <div class="profile_sort">
    	<p>Sort by: DROP DOWN</p>
    </div>
    <!--Get paper 1-->

    	<div class="paper">

            <div class="paper_image">
        	<img src="http://i.imgur.com/GRbsrKN.jpg" />
            </div>

            <div class="paper_text">
            	<div class="paper_title" style="font-weight: 700;">
            		<p>Publication Title</p>
            	</div>

                <div class="paper_edition">
                    <p>Publication Edition</p>
                </div>

                <div class="paper_condition">
                    <p>Condition out of 10</p>
                </div>

                <div class="tradebutton">
                <a href="/">Offer Trade</a>
                </div>

            </div>
    		<!--Make one-column layout populate with all of [profile]'s paper for trade.-->

        </div>

        <!--END Paper 1-->

        <!--Get paper 1-->

    	<div class="paper">

            <div class="paper_image">
        	<img src="http://i.imgur.com/GRbsrKN.jpg" />
            </div>

            <div class="paper_text">
            	<div class="paper_title">
            		<p>The Plant Journal</p>
            	</div>

                <div class="paper_edition">
                    <p>Issue 02</p>
                </div>

                <div class="paper_condition">
                    <p>9 / 10</p>
                </div>

                <div class="tradebutton">
                <a href="/">Offer Trade</a>
                </div>

            </div>
    		<!--Make one-column layout populate with all of [profile]'s paper for trade.-->

        </div>

        <!--END Paper 1-->

        <!--Get paper 1-->

    	<div class="paper">

            <div class="paper_image">
        	<img src="http://i.imgur.com/GRbsrKN.jpg" />
            </div>

            <div class="paper_text">
            	<div class="paper_title">
            		<p>The Plant Journal</p>
            	</div>

                <div class="paper_edition">
                    <p>Issue 02</p>
                </div>

                <div class="paper_condition">
                    <p>9 / 10</p>
                </div>

                <div class="tradebutton">
                <a href="/">Offer Trade</a>
                </div>

            </div>
    		<!--Make one-column layout populate with all of [profile]'s paper for trade.-->

        </div>

        <!--END Paper 1-->
        <!--Get paper 1-->

    	<div class="paper">

            <div class="paper_image">
        	<img src="http://i.imgur.com/GRbsrKN.jpg" />
            </div>

            <div class="paper_text">
            	<div class="paper_title">
            		<p>The Plant Journal</p>
            	</div>

                <div class="paper_edition">
                    <p>Issue 02</p>
                </div>

                <div class="paper_condition">
                    <p>9 / 10</p>
                </div>

                <div class="tradebutton">
                <a href="/">Offer Trade</a>
                </div>

            </div>
    		<!--Make one-column layout populate with all of [profile]'s paper for trade.-->

        </div>

        <!--END Paper 1-->
        <!--Get paper 1-->

    	<div class="paper">

            <div class="paper_image">
        	<img src="http://i.imgur.com/GRbsrKN.jpg" />
            </div>

            <div class="paper_text">
            	<div class="paper_title">
            		<p>The Plant Journal</p>
            	</div>

                <div class="paper_edition">
                    <p>Issue 02</p>
                </div>

                <div class="paper_condition">
                    <p>Condition: 9 / 10</p>
                </div>

                <div class="tradebutton">
                <a href="/">Offer Trade</a>
                </div>

            </div>
    		<!--Make one-column layout populate with all of [profile]'s paper for trade.-->

        </div>

        <!--END Paper 1-->

</div>
<!--End Profile Content-->

<div class="bottom"></div>
</body>
</html>

users/templates/paperapp/register.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Register - trade–paper</title>
	{% load staticfiles %}
	<link href="{% static 'paperapp/styles.css' %}" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>
</head>

<body>

{% include "paperapp/nav-bar.html" %}

<!--Sign Up-->
<div class="register">
	<h1>Sign Up</h1>
	{% if error_message %}<h2>{{ error_message }}</h2>{% endif %}
	<form action="{% url 'users:register' %}" method="post">
		{% csrf_token %}
	    <h2>Pick a username:</h2>
	    <!--text form here-->
		<input type="text" name="username" placeholder="username" id="register_username" data-required="required" class="textfield_effect">

	    <h2>Choose a password:</h2>
	    <!--text form here-->
		<input type="password" name="password" placeholder="password" id="register_password" data-required="required" class="textfield_effect">

	    <h2>Enter your email address:</h2>
	    <!--text form here-->
		<input type="email" name="email" placeholder="email address" id="register_email" data-required="required" class="textfield_effect">

		<input type="submit" value="Submit" class="textfield_effect" id="register_submit">
	</form>
</div>
<!--END Sign Up-->

<div class="bottom"></div>
</body>
</html>

users/templates/paperapp/signup.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Register - trade–paper</title>
	{% load staticfiles %}
	<link href="{% static "paperapp/styles.css" %}" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>
</head>

<body>

{% include "paperapp/nav-bar.html" %}

<!--Sign Up-->
<div class="signup">
	<h1>Sign Up</h1>
	{% if error_message %}<h2>{{ error_message }}</h2>{% endif %}
	<form action="/register/" method="post">
		{% csrf_token %}
	    <h2>Pick a username:</h2>
	    <!--text form here-->
		<input type="text" name="username" placeholder="username" id="signup_username" data-required="required" class="textfield_effect">

	    <h2>Choose a password:</h2>
	    <!--text form here-->
		<input type="text" name="password" placeholder="password" id="signup_password" data-required="required" class="textfield_effect">

	    <h2>Enter your email address:</h2>
	    <!--text form here-->
		<input type="email" name="email" placeholder="email address" id="signup_email" data-required="required" class="textfield_effect">

		<input type="submit" value="Submit" class="textfield_effect" id="signup_submit">
	</form>
</div>
<!--END Sign Up-->

<div class="bottom"></div>
</body>
</html>